name: SwimmingApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: 15.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.swimming.attendance.ios
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    TARGETED_DEVICE_FAMILY: 1
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    CODE_SIGN_STYLE: Automatic
packages: {}
targets:
  SwimmingApp:
    type: application
    platform: iOS
    sources:
      - path: SwimmingApp
    settings:
      base:
        INFOPLIST_FILE: SwimmingApp/Info.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    scheme:
      testTargets: []
    postCompileScripts: []
    postBuildScripts: [] 